version: "3"
services:
  mysqldb:
    container_name: mysqldb
    image: mysql:latest
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE_USERNAME: root
      MYSQL_ROOT_PASSWORD: faresmekni
      MYSQL_DATABASE: kaddem
    volumes:
      - db_vol:/var/lib/mysqldb

  Department_app:
    build: .
    image: faresmekni-5twin5-g6
    restart: unless-stopped
    ports:
      - "8089:8089"
    depends_on:
      - mysqldb

volumes:
  db_vol:
