### STAGE 1: BUILD ###
FROM node:14.17.3 AS build
WORKDIR /dist/src/app
COPY . .
RUN npm install -g @angular/cli
RUN npm cache clean --force
RUN npm install --force
RUN ng build --prod

### STAGE 2: RUN ###
FROM nginx:latest AS ngi
COPY --from=build /dist/src/app/dist/crudtuto-Front /usr/share/nginx/html
COPY /nginx.conf  /etc/nginx/conf.d/default.conf
EXPOSE 86
