### STAGE 1: BUILD ###
FROM node:16.16-alpine AS build
WORKDIR /app
COPY . .
RUN npm install -g @angular/cli@16.2.6
RUN npm cache clean --force
RUN npm install --force

# Configuration du proxy npm (ajustez en fonction de vos paramètres)
RUN npm config set registry "https://registry.npmjs.org/"
RUN npm config set proxy http://your-proxy-server:your-proxy-port
RUN npm config set https-proxy http://your-proxy-server:your-proxy-port

# Utilisez --configuration=production au lieu de --prod
RUN ng build --configuration=production

### STAGE 2: RUN ###
FROM nginx:latest AS ngi
COPY --from=build /app/dist/crudtuto-Front /usr/share/nginx/html
COPY /nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 86
