# Use the official Node image as a base image
FROM node:18.13.0

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install app dependencies
RUN npm install --force

# Copy the entire project to the working directory
COPY . .

# Build the Angular app
RUN npm run build

# Expose the port the app will run on
EXPOSE 4200

# Define the command to run the app
CMD ["npm", "start"]
